/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.blood;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Donor extends javax.swing.JFrame {

    /**
     * Creates new form Donor
     */
    public Donor() {
        initComponents();
    }
    
    
  

    
   private String data;
   private void nextFrame(){
        new Donor1().setVisible(true);
                  this.setVisible(false);
                  this.dispose();
                  Donor1.DisplayEdit();
                  Donor1.getvalue(data);
    }
    
      private void searchFrame(){
        new DonorSearch().setVisible(true);
                  this.setVisible(false);
                  this.dispose();
                //  Donor_Search d=new Donor_Search();
                 DonorSearch.viewdata(data);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnOK1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor ID", "NIC No" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 110, 30));

        btnSearch.setBackground(new java.awt.Color(255, 0, 0));
        btnSearch.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, -1));

        jComboBox2.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor ID", "Nic No", "Blood Bank ID", "Blood Group", "City" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 120, 30));

        jLabel4.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel4.setText("Search By : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 80, 14));

        jLabel5.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel5.setText("Make changes by");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, -1));

        btnOK1.setBackground(new java.awt.Color(255, 0, 0));
        btnOK1.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnOK1.setForeground(new java.awt.Color(255, 255, 255));
        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 60, -1));

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 20));

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel2.setText("Check id Donor existing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel3.setText("Enter NIC No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 30));

        btnHome.setBackground(new java.awt.Color(255, 0, 0));
        btnHome.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 73, -1));

        btnok.setBackground(new java.awt.Color(255, 0, 0));
        btnok.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnok.setForeground(new java.awt.Color(255, 255, 255));
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        getContentPane().add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 60, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new Donor1().setVisible(true);
        this.setVisible(false);
        this.dispose();
        Donor1.Display();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();

            String id= jTextField1.getText();
            String sql="SELECT * FROM donor where d_nic_no='"+id+"'";
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()){
            String user=rs.getString("donor_id");
            JOptionPane.showMessageDialog(this,"Donor already exists as "+user);
            }
            else{
            JOptionPane.showMessageDialog(this,"Donor doesn't exist,click the add button to add");
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
}
        
        //viewcombo();
    }//GEN-LAST:event_btnokActionPerformed

    
    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
      
             try{
        DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
        Statement stmt=c.createStatement();

             switch (jComboBox1.getSelectedIndex()) {
                 case 0:
                     data="Enter Donor ID";
                     
                 
                     nextFrame();
                     
                     break;
                 case 1:
                     data="Enter Nic No";
                     
                     //d.getvalue(data);

                     nextFrame();
                     
                     break;
                 
                 default:
                     break;
             }
c.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        
        
        
        /*try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();

            String id= jTextField2.getText();
            String sql="SELECT * FROM donor where d_nic_no='"+id+"' or donor_id='"+id+"'" ;
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()){
                new Donor1().setVisible(true);
                this.setVisible(false);
                this.dispose();
                String did=(rs.getString("donor_id"));
               String bid=(rs.getString("blood_bank_id"));
               String nicno=(rs.getString("d_nic_no"));
              String name=(rs.getString("d_name"));
               String address=(rs.getString("d_address"));
               String city=(rs.getString("city"));
               String bg=(rs.getString("d_blood_group"));
               String gender=(rs.getString("d_gender"));
               String mno=(rs.getString("d_mobile_no"));
               String email=(rs.getString("d_email"));
               String dob=(rs.getString("d_dob"));
               d.getvalue(did,bid,nicno,name,address,city,bg,gender,mno,email,dob);
                
                Donor1 d=new Donor1();
                d.getvalue(id);
                
                
            //String user=rs.getString("donor_id");
            
            //JOptionPane.showMessageDialog(this,"Donor already exists as "+user);
            }
            else{
            JOptionPane.showMessageDialog(this,"Donor doesn't exist,click the add button to add");
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }*/
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       try{
        DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
        Statement stmt=c.createStatement();

             switch (jComboBox2.getSelectedIndex()) {
                 case 0:
                     data="Enter Donor ID";
                     searchFrame();
                     //  Donor_Search.viewdata(data);
                     break;
                 case 1:
                     data="Enter Nic No";
                     searchFrame();
                     
                     break;
                 case 2:
                     data="Enter Blood Bank Id";
                     searchFrame();
                     break;
                 case 3:
                     data="Enter Blood Group";
                     searchFrame();
                     break;
                     case 4:
                     data="Enter City";
                     searchFrame();
                     break;
                 default:
                     break;
             }
c.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formComponentShown

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
