/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.blood;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class Donor1 extends javax.swing.JFrame {

    /**
     * Creates new form Donor1
     */
    
   
    public Donor1() {
        initComponents();
        viewcombo();
         
        
    }
   
    //private static String data;
    public static void getvalue(String data){
       jLabel13.setText(data);    
       
       // jTextField1.setText(data);
    }
    
    public static void viewcombo(){
        try{
        DBconnection cd=new DBconnection();
        Connection c=cd.getDBConnection();
        Statement stmt=c.createStatement();

        String sql="Select * from blood_bank";
        ResultSet rs=stmt.executeQuery(sql);
        while(rs.next()){

            jComboBox3.addItem(rs.getString("Blood_bank_id"));
        }
        c.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
   
    public static void Display(){
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        
    }
    
    public static void DisplayEdit(){
        jPanel2.setVisible(false);
               
    }
    
    Validation validation=new Validation();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btndelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndelete)
                .addGap(16, 16, 16)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 500, 60));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 381));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel2.setText("Donor Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(51, 43, 88, 15);

        jLabel3.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel3.setText("Blood Bank id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(51, 83, 89, 15);

        jLabel4.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(51, 136, 56, 15);

        jLabel5.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel5.setText("NIC no");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(348, 43, 42, 15);

        jLabel6.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel6.setText("DOB");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(348, 83, 34, 15);

        jLabel7.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(51, 175, 70, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(157, 36, 126, 29);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(414, 36, 140, 29);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(160, 130, 126, 28);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(131, 175, 204, 76);

        jLabel8.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(348, 136, 62, 15);

        jLabel9.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel9.setText("City");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(51, 277, 34, 15);

        jLabel10.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel10.setText("Blood Group");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(374, 192, 91, 15);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(436, 83, 140, 28);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(469, 185, 127, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ampara", "Anuradhapura", "Badulla", "Batticaloa", "Colombo", "Galle", "Gampaha", "Hambantota", "Jaffna", "Kalutara", "Kandy", "Kegalle", "Kilinochchi", "Kurunegala", "Mannar", "Matale", "Matara", "Monaragala", "Mullaitivu", "Nuwara Eliya", "Polonnaruwa", "Puttalam", "Ratnapura", "Trincomalee", "Vavuniya" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(154, 269, 134, 30);

        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(157, 83, 126, 28);

        jLabel11.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(374, 230, 40, 15);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(469, 223, 130, 28);

        jLabel12.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel12.setText("Mobile No");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(374, 277, 79, 15);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(471, 269, 84, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(436, 129, 140, 28);

        jLabel14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel14KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(471, 305, 114, 13);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 370);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 610, 370));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 83, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       
        try{ 
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
            String did=jTextField1.getText();
            String bbid=jComboBox3.getSelectedItem().toString();
            String nicno= jTextField2.getText();
            String name=jTextField5.getText();
            String address=jTextArea1.getText();
            String city=jComboBox2.getSelectedItem().toString();
            String dob=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            String gender=jComboBox4.getSelectedItem().toString();
            String bgroup=jComboBox1.getSelectedItem().toString();
            String email=jTextField3.getText();
            String mno=jTextField4.getText();
            if(!(validation.emailValid(email))){
                    JOptionPane.showMessageDialog(this,"ENTER VALID EMAIL!!");
                }else{
                    if(validation.integerValid(mno,"mobile no")==0){
                    String sql1="insert into donor (donor_id,Blood_bank_Id,d_nic_no,d_name,d_address,city,d_dob,d_gender,d_blood_group,d_email,d_mobile_no) VALUES ('"+did+"','"+bbid+"', '"+nicno+"', '"+name+"','"+address+"','"+city+"','"+dob+"','"+gender+"','"+bgroup+"','"+email+"','"+mno+"');";

                    stmt.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(this,"1 ITEM ADDED");
                    }else{
                        
                    }
                    
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
    
    
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
  
            
            try{
                DBconnection cd=new DBconnection();
                Connection c=cd.getDBConnection();
                Statement stmt=c.createStatement();
                String did=jTextField1.getText();
                String bbid=jComboBox3.getSelectedItem().toString();
                String nicno= jTextField2.getText();
                String name=jTextField5.getText();
                String address=jTextArea1.getText();
                String city=jComboBox2.getSelectedItem().toString();
                String dob=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                String gender=jComboBox4.getSelectedItem().toString();
                String bgroup=jComboBox1.getSelectedItem().toString();
                String email=jTextField3.getText();
                String mno=jTextField4.getText();
                
                if(!(validation.emailValid(email))){
                    JOptionPane.showMessageDialog(this,"ENTER VALID EMAIL!!");
                }else{
                    if(validation.integerValid(mno,"mobile no")==0){
                    String sql1="update donor set blood_bank_id='"+bbid+"',d_nic_no='"+nicno+"',d_name='"+name+"',d_address='"+address+"',city='"+city+"',d_dob='"+dob+"',d_gender='"+gender+"',d_blood_group='"+bgroup+"',d_email='"+email+"',d_mobile_no='"+mno+"' where donor_id='"+did+"' ";
                
                    stmt.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(this,"RECORD UPDATED");
                    }else{
                        
                    }
                }
            c.close();
            }

            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
            
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
       
        int dialogButton=JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Delete this data","Delete",dialogButton);
        if(dialogResult==0){
        try{
        DBconnection cd=new DBconnection();
        Connection c=cd.getDBConnection();
        Statement stmt=c.createStatement();
        
        String sql1="delete from donor where donor_id='"+jTextField6.getText()+"' or d_nic='"+jTextField6.getText()+"'";
        stmt.executeUpdate(sql1);
        JOptionPane.showMessageDialog(this,"RECORD DELETED");
        c.close();
        }

        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
       
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
          
            String sql="SELECT * FROM donor where d_nic_no='"+jTextField6.getText()+"' or donor_id='"+jTextField6.getText()+"'" ;
            ResultSet rs=stmt.executeQuery(sql);
            
            if(rs.next()){
                         
               jTextField1.setText(rs.getString("donor_id"));
                jComboBox3.setSelectedItem(rs.getString("blood_bank_id"));
               jTextField2.setText(rs.getString("d_nic_no"));
              jTextField5.setText(rs.getString("d_name"));
               jTextArea1.setText(rs.getString("d_address"));
               jComboBox2.setSelectedItem(rs.getString("city"));
               jComboBox1.setSelectedItem(rs.getString("d_blood_group"));
               jComboBox4.setSelectedItem(rs.getString("d_gender"));
               jTextField4.setText(rs.getString("d_mobile_no"));
               jTextField3.setText(rs.getString("d_email"));
               ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(rs.getString("d_dob"));
               
            }
            
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new Donor().setVisible(true);
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
            try{
        
        jTextField1.setEditable(false);
        AutoIncrement aid=new AutoIncrement();
        String donor_id=aid.getPrimaryKey("DN","SELECT donor_id FROM donor ORDER BY donor_id DESC LIMIT 1");
        jTextField1.setText(donor_id);
 
        }

        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel14KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel14KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
         try{

        Integer.parseInt(jTextField4.getText());
        jLabel14.setText("");
        }

        catch (NumberFormatException e){
            jLabel14.setText("Enter Integer only");
       
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor1().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private static javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private static javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
