/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.blood;

import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDonor = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnBlood = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnStaff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDonor.setBackground(new java.awt.Color(255, 0, 0));
        btnDonor.setFont(new java.awt.Font("Nexa Light", 0, 12)); // NOI18N
        btnDonor.setForeground(new java.awt.Color(255, 255, 255));
        btnDonor.setText("Donor");
        btnDonor.setMaximumSize(new java.awt.Dimension(75, 25));
        btnDonor.setMinimumSize(new java.awt.Dimension(75, 25));
        btnDonor.setPreferredSize(new java.awt.Dimension(75, 25));
        btnDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        btnHospital.setBackground(new java.awt.Color(255, 0, 0));
        btnHospital.setFont(new java.awt.Font("Nexa Light", 0, 12)); // NOI18N
        btnHospital.setForeground(new java.awt.Color(255, 255, 255));
        btnHospital.setText("Hospitals");
        btnHospital.setMaximumSize(new java.awt.Dimension(75, 25));
        btnHospital.setMinimumSize(new java.awt.Dimension(75, 25));
        btnHospital.setPreferredSize(new java.awt.Dimension(75, 25));
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 85, -1));

        btnBlood.setBackground(new java.awt.Color(255, 0, 0));
        btnBlood.setFont(new java.awt.Font("Nexa Light", 0, 12)); // NOI18N
        btnBlood.setForeground(new java.awt.Color(255, 255, 255));
        btnBlood.setText("Blood");
        btnBlood.setMaximumSize(new java.awt.Dimension(75, 25));
        btnBlood.setMinimumSize(new java.awt.Dimension(75, 25));
        btnBlood.setPreferredSize(new java.awt.Dimension(75, 25));
        btnBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodActionPerformed(evt);
            }
        });
        getContentPane().add(btnBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        btnOrder.setBackground(new java.awt.Color(255, 0, 0));
        btnOrder.setFont(new java.awt.Font("Nexa Light", 0, 12)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("Order");
        btnOrder.setMaximumSize(new java.awt.Dimension(75, 25));
        btnOrder.setMinimumSize(new java.awt.Dimension(75, 25));
        btnOrder.setPreferredSize(new java.awt.Dimension(75, 25));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 360, 100, -1));

        jTable1.setBackground(new java.awt.Color(255, 51, 51));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A+", "           ."},
                {"A-", ""},
                {"B+", null},
                {"B-", null},
                {"O+", null},
                {"O-", null},
                {"AB+", null},
                {"AB-", null}
            },
            new String [] {
                "           Blood Group", "           Quantity"
            }
        ));
        jTable1.setAlignmentX(1.5F);
        jTable1.setAlignmentY(1.5F);
        jTable1.setGridColor(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 360, 160));

        btnStaff.setText("Staff");
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\2nd semi\\Database Design and Development\\project\\interface\\home page.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 403));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorActionPerformed
        // TODO add your handling code here:
        new Donor().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnDonorActionPerformed

    private void btnBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodActionPerformed
        // TODO add your handling code here:
        new Bloodt().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBloodActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
        new Hospital().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        new Order().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
            String sql="SELECT donor.D_BLOOD_GROUP, SUM(blood.BLOOD_QUANTITY) AS Quantity FROM donor, blood WHERE donor.DONOR_ID=blood.Donor_ID GROUP BY donor.D_BLOOD_GROUP";
            ResultSet rs=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            JTableHeader th = jTable1.getTableHeader();
            th.setFont(new Font("Serif", Font.BOLD, 15));
            while(rs.next()){
            String id=rs.getString("d_blood_group");
            String name=rs.getString("quantity");
            String tbData[]={id,name};


            model.addRow(tbData);
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_formComponentShown

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        new Staff().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlood;
    private javax.swing.JButton btnDonor;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
