/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.blood;

import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class Hospital extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
      
    }
   //private void TextBox(){
     //  if(jTextField5.getText().length()==0 )
      
  // }
    Validation validation=new Validation();
    
        public void view(){
            try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
            String sql="Select * from hospital where HOSPITAL_ID='"+jTextField6.getText()+"' ";
            ResultSet rs=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            JTableHeader th = jTable1.getTableHeader();
            th.setFont(new Font("Serif", Font.BOLD, 15));
            while(rs.next()){
            String id=rs.getString("Hospital_id");
            String name=rs.getString("hs_name");
            String address=rs.getString("hs_address");
            String email=rs.getString("hs_email");
            String telno=rs.getString("tel_no");
            String tbData[]={id,name,address,email,telno};


            model.addRow(tbData);
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 410));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 0, 0));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital ID", "Name", "Address", "Email", "Tel No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 450, 220));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        jLabel2.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel2.setText("Hospital Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 14));

        jLabel3.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, -1));

        jLabel4.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, 70, 20));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, -1));

        jLabel6.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel6.setText("Tel No 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, -1));

        jLabel5.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        jTextField5.setText("0");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, -1));

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 60, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 30));

        jLabel7.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        jLabel7.setText("Enter Hospital Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 90, -1));

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, -1));

        btnOk.setBackground(new java.awt.Color(255, 0, 0));
        btnOk.setFont(new java.awt.Font("Nexa Light", 0, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        btnHome.setBackground(new java.awt.Color(255, 0, 0));
        btnHome.setFont(new java.awt.Font("Nexa Light", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 73, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\2nd semi\\Database Design and Development\\project\\interface\\bg dinal.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
            String id=jTextField1.getText();
            //String Bid=jComboBox1.getSelectedItem().toString();
            String name= jTextField2.getText();
            String address=jTextArea1.getText();
            String email=jTextField4.getText();
            String telno1=jTextField5.getText();
            if(!(validation.emailValid(email))){
                    JOptionPane.showMessageDialog(this,"ENTER VALID EMAIL!!");
                }else{
                 if(validation.integerValid(telno1,"tel no")==0){
                    String sql1="insert into hospital (hospital_id,hs_name,hs_address,hs_email,tel_no) VALUES ('"+id+"', '"+name+"', '"+address+"','"+email+"','"+telno1+"');";

                    stmt.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(this,"1 ITEM ADDED");
                 }
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
            view();
            
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();

            String id= jTextField6.getText();
            String sql="SELECT * FROM hospital where HOSPITAL_ID='"+jTextField6.getText()+"'";
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()){
                jTextField1.setText(rs.getString("hospital_id"));
                jTextField2.setText(rs.getString("HS_Name"));
                //jComboBox1.setSelectedItem(rs.getString("blood_bank_id"));
                jTextArea1.setText(rs.getString("HS_Address"));
                jTextField4.setText(rs.getString("HS_email"));
                jTextField5.setText(rs.getString("Tel_no"));
             
                
            }
            else{
            JOptionPane.showMessageDialog(this,"Hospital doesn't exist");
            }
            c.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            DBconnection cd=new DBconnection();
            Connection c=cd.getDBConnection();
            Statement stmt=c.createStatement();
            String email=jTextField4.getText();
            String telno=jTextField5.getText();
            if(!(validation.emailValid(email))){
                    JOptionPane.showMessageDialog(this,"ENTER VALID EMAIL!!");
                }else{
                     if(validation.integerValid(telno,"tel no")==0){
                    String sql1="update hospital set hospital_id='"+jTextField1.getText()+"',hs_name='"+jTextField2.getText()+"',hs_address='"+jTextArea1.getText()+"',hs_email='"+jTextField4.getText()+"',tel_no='"+jTextField5.getText()+"' where hospital_id='"+jTextField1.getText()+"'";

                    stmt.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(this,"RECORD UPDATED");
                     }
            }
            c.close();
            }

            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
            
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int dialogButton=JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Delete this data","Delete",dialogButton);
        if(dialogResult==0){
        try{
        DBconnection cd=new DBconnection();
        Connection c=cd.getDBConnection();
        Statement stmt=c.createStatement();
        String sql1="delete from hospital where hospital_id='"+jTextField6.getText()+"'";
        
        stmt.executeUpdate(sql1);
        c.close();
        }

        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        JOptionPane.showMessageDialog(this,"RECORD DELETED");
        view();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
       
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
        
        jTextField1.setEditable(false);
        AutoIncrement aid=new AutoIncrement();
        String hospital_id=aid.getPrimaryKey("HS","SELECT hospital_id FROM hospital ORDER BY hospital_id DESC LIMIT 1");
        jTextField1.setText(hospital_id);
        view();
        }

        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
